apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthznerbot
  namespace: personal
spec:
  selector:
    matchLabels:
      app: healthznerbot
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: healthznerbot
    spec:
      containers:
      - name: healthznerbot
        image: registry.raphaelbernhart.at/raphaelbernhart/healthznerbot:1.1.0
        env:
        - name: NODE_ENV
          value: production
        - name: STATUS_UPDATE_INTERVAL
          value: '5'
        - name: SERVER_METRICS_PERIOD
          value: '2.5'
        - name: LANGUAGE
          value: 'de'
        - name: MEME_MODE
          value: 'true'
        - name: GIPHY_API_KEY
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: GIPHY_API_KEY
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: DISCORD_TOKEN
        - name: DISCORD_CHANNEL
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: DISCORD_CHANNEL
        - name: HETZNER_TOKEN_1
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: HETZNER_TOKEN_1
        - name: HETZNER_TOKEN_2
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: HETZNER_TOKEN_2
        imagePullPolicy: Always
        resources:
          requests:
            memory: 65M"
            cpu: "30m"
          limits:
            memory: "100M"
            cpu: "50m"
      imagePullSecrets:
      - name: regcred