apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthznerbot
  namespace: personal
spec:
  selector:
    matchLabels:
      app: healthznerbot
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: healthznerbot
    spec:
      containers:
      - name: healthznerbot
        image: registry.raphaelbernhart.at/raphaelbernhart/healthznerbot:0.0.2
        env:
        - name: NODE_ENV
          value: production
        - name: STATUS_UPDATE_INTERVAL
          value: '1'
        - name: SERVER_METRICS_PERIOD
          value: '15'
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: DISCORD_TOKEN
        - name: DISCORD_CHANNEL
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: DISCORD_CHANNEL
        - name: HETZNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: healthznerbot-secrets
              key: HETZNER_TOKEN
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100M"
            cpu: "100m"
      imagePullSecrets:
      - name: regcred